### ISSUE TITLE
cursor

### ISSUE THREAD

**Issue by aman-singh-unthinkable** [tttstudios/react-native-otp-input#116]
not able to change cursor color and also cursor alignment is also wrong when we delete an element from the input field

**Comment by fpena** [comment]
@fpena can you please provide a working code example and your expectation? Thanks.

**Comment by KamranAshiq** [comment]
> not able to change cursor color and also cursor alignment is also wrong when we delete an element from the input field

facing same problem on clearing a input field cursor does not blink in the centre of input field.

**Comment by t3chcrazy** [comment]
You can change the cursor color with the `selectionColor` prop of the OTPInputView

**Comment by Sunnysit** [comment]
Hi @aman-singh-unthinkable, 

as @t3chcrazy mentioned, please use `selectionColor` prop to change cursor color. 

For the cursor alignment, it would be center if there is no `placeholderCharacter` value. Otherwise, the cursor would show beside the placeholderCharacter (left side in iOS or right side in Android).

**Comment by muhammadwasi81** [comment]
<OTPInputView
              style={{ width: '80%' }}
              pinCount={4}
              autoFocusOnLoad
              code={code}
              onCodeChanged={code => setCode(code)}
              codeInputFieldStyle={styles.underlineStyleBase}
              codeInputHighlightStyle={styles.underlineStyleHighLighted}
              placeholderTextColor={COLORS.black}
              selectionColor={COLORS.main}
              keyboardType="number-pad"
              onCodeFilled={code => {
                console.log(`Code is ${code}, you are good to go!`)
                setCode(code)
              }}
            />

This provide me the backgroundColor when I enter last input field does anyone have the solution?
