### ISSUE TITLE
How to manage spacing between the pin entered and the blank. 

### ISSUE THREAD

**Issue by shukla12manish** [tttstudios/react-native-otp-input#13]
Not able to reduce the spacing between code entered and the blank.

When i used the library the spacing between the code entered and the blank is too much. So my query is how to reduce that gap.

**To Reproduce**
Just use the library in your code and the default spacing between the code entered and the blank is too much.

**Expected behavior**
It can be managed with the help of css

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: MI Max 2
 - OS: Android 7.1.1

**Additional context**
I want to know how to manage the spacing between the filling blank and the code entered.

**Comment by fpena** [comment]
Hi @shukla12manish 
Can you explain with a screenshot which space you want to reduce? 
This is probably achievable with a style prop passed to the component.

**Comment by shukla12manish** [comment]
Kindly find the snapshot. I cannot post the whole screen but i have cropped it.
![IMG_20191110_210916](https://user-images.githubusercontent.com/29957588/68546665-eeba8880-03fe-11ea-9b92-32713deb6da3.jpg)

**Comment by fpena** [comment]
Can you indicate with an arrow (with a new image) which space is it?

**Comment by shukla12manish** [comment]
I have marked the space between the digit and dash. I want to shorten this gap.
![IMG_20191110_231245](https://user-images.githubusercontent.com/29957588/68548281-29c5b780-0411-11ea-8a79-225029dd2075.jpg)

**Comment by fpena** [comment]
I see! They way you can do that is by reducing the height of the container.
By default, the container has `45` for height. 
If you use the `codeInputFieldStyle` prop and send a lower one, then the digit will become closer to the bottom line.

**Comment by shukla12manish** [comment]
I have passed underlineStyleBase in codeInputFieldStyle which i am sharing:

`underlineStyleBase: {
      width: 40,
      height: 60,
      borderWidth: 0,
      borderBottomWidth: 2,
      color: Colors.whiteFF,
      fontSize: 25,
      fontFamily: Fonts.type.light,
      textAlign: 'center',
    },`

When i alter the height it hides the font but there is no change in the space between.

**Comment by shubh007-dev** [comment]
@shukla12manish were you able to solve this issue? I'm facing the same problem.

**Comment by ericdao-ttt** [comment]
Hi @shukla12manish 

Can you add paddingBottom: 0 to underlineStyleBase?

Thank you

**Comment by vinaynarayankutty** [comment]
@shukla12manish Hi, how do I change the default background colour? Whenever the otp input is filled the background colour gets changed to grey colour. I've added background colour in codeinput style and all still I'm getting this problem. Is there a solution?
