### ISSUE TITLE
On Android keyboard does not show up

### ISSUE THREAD

**Issue by devcoderbuzz** [tttstudios/react-native-otp-input#160]
On an Android device if on the previous screen, the keyboard is opened and then navigated to this OTP screen, then the keyboard is shown.

But if the keyboard is not opened and then navigated to this screen, then the keyboard does not show in spite of clicking the text box.

**Comment by oguzturker8** [comment]
having same problem

**Comment by RajRohitYadav** [comment]
facing same issue

**Comment by devcoderbuzz** [comment]
> having same problem

I dumped this component and went with different one "react-native-confirmation-code-input"

**Comment by devcoderbuzz** [comment]
> > having same problem

I dumped this component and went with different one "react-native-confirmation-code-input"

**Comment by devcoderbuzz** [comment]
I have migrated to a different component.   "react-native-confirmation-code-input" is lot stable and good

**Comment by devcoderbuzz** [comment]
I have migrated to a different component. "react-native-confirmation-code-input" is lot stable and good

**Comment by oguzturker8** [comment]
I solved the problem with following workaround 

- Declare a ref
`const inputRef = useRef<OTPInputView>(null)`
- set autoFocusOnLoad false
`<OTPInputView autoFocusOnLoad={false ... />`
- call focusField function with 0 index param inside useEffect
` useEffect(() => {
 if (inputRef.current) inputRef?.current?.focusField(0)
  }, [])`

**Comment by RajRohitYadav** [comment]
I solved the problem by making focus async

in method foucusField added
```
 setTimeout(() => {
    this.fields[index].focus();
 });
```
       
 replace the method as below to make it work

```
    this.focusField = index => {
      if (index < this.fields.length) {
        setTimeout(() => {
          this.fields[index].focus();
        });
        this.setState({
          selectedIndex: index,
        });
      }
    };
```
