### ISSUE TITLE
Error while running on android

### ISSUE THREAD

**Issue by agucchristopher** [tttstudios/react-native-otp-input#198]
**Describe the bug**
After i installed the otp input in android and used it , it kept on logging error to my console
**To Reproduce**
1. Install the package
2. Import it
3. Try and use it

**Expected behavior**
For it to run normally
**Smartphone (please complete the following information):**
 - Device: Tecno F6
 - OS: Android 7
 - Browser Chrome

**Comment by hoangkien07051** [comment]
you need add dependency @react-native-community/clipboard
