### ISSUE TITLE
on unlocking otp screen, it's autofill otp from messages but second last otp filled not latest.

### ISSUE THREAD

**Issue by rmamtaventures** [tttstudios/react-native-otp-input#26]
**Describe the bug**
Second last otp autofill on unlocking the screen in android devices.

**To Reproduce**
1. Go to otp screen,
2. Lock the screen,
3. Unlock the screen.
4. Second last otp from messages filled.

**Expected behavior**
Latest otp should be auto fill.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. One plus5t]
 - OS: [e.g. android 9]

**Additional context**

**Comment by Sajid-Ali** [comment]
any luck with this?

**Comment by ericdao-ttt** [comment]
Hi @rmamtaventures 

I think this issue is because the app is in background, therefore, it cannot recognize the latest message.

**Comment by sajid-ad** [comment]
Any luck?

**Comment by tal32123** [comment]
app in foreground also has issues

**Comment by sajid-ad** [comment]
@tal32123 this is because app tries to read text from the clipboard if you have already copied something in the clipboard that I will read from the there. Just clear the clipboard and check it will not behave like this. Need to use lib to read from SMS instead of the clipboard.

**Comment by Sajid-Ali** [comment]
@tal32123 This is because app tries to read text from the clipboard if you have already copied something in the clipboard that I will read from the there. Just clear the clipboard and check it will not behave like this. Need to use lib to read from SMS instead of the clipboard.

**Comment by tal32123** [comment]
I read about this issue, is there any way to have it read the latest thing copied in clipboard? 

@sajid-ad  Do you know if this is something that is currently being worked on in this library? Should I use a different one?

**Comment by Sajid-Ali** [comment]
@tal32123 Actually its read the latest copied item from the clipboard, its behave differently because users have copied many things in the clipboard it will just fetch the latest copied string/number base on input type and opt code length you defined. 

As mentioned the documentation for ios it will show the suggestion, but for ab=ndroid you have to use the SMS Retriever API, and that works perfectly

> The iOS input suggestion requires React Native 0.58+ and works for iOS 12 and above.
> 
> On Android, it will be auto-filled when you press the copy code button in the notification bar (see above GIF). It will do so only if the code is sent after the view is loaded. So make sure you request the code AFTER this view is loaded.
> 
> If you are interested in Android SMS Retriever API, we would suggest @Faizal's repo React-Native-OTP-Verify. It looks pretty cool and it should be straight-forward to use React-Native-OTP-Verify along with this library.

[here is the link](https://github.com/faizalshap/react-native-otp-verify) you can use this to read otp from SMS

**Comment by rutul089** [comment]
> I read about this issue, is there any way to have it read the latest thing copied in clipboard?
> 
> @sajid-ad Do you know if this is something that is currently being worked on in this library? Should I use a different one?

Did you find any solution for that?
