### ISSUE TITLE
First input is filled with all the numbers in ios

### ISSUE THREAD

**Issue by rajatgalav** [tttstudios/react-native-otp-input#34]
I am using OTPInputView for ios.

                <OTPInputView
                        style={{width: '80%', height: 200}}
                        pinCount={6}
                        codeInputFieldStyle={{
                            fontSize: 18,
                            width: 30,
                            height: 45,
                            borderWidth: 0,
                            borderBottomWidth: 1,
                        }}
                        codeInputHighlightStyle={{borderColor: "#03DAC6",}}
                        onCodeFilled = {(code) => this.verify(code)}
                    />

When i click on keyboard clipboard to read otp, whole value is filled in first input field and only last two numbers are shown in the input field.
After some time it spread to whole 6 input fields.

**Comment by Zhark10** [comment]
same problem

**Comment by AndriiBoiko** [comment]
Hi!
Any updates?

**Comment by fareedagha** [comment]
any updated? facing same issue

**Comment by dcosmin2003** [comment]
This issue is also visible on the demo GIF :)

**Comment by Nikualla1** [comment]
Why is this closed?
