### ISSUE TITLE
clearInputs is not working properly and there is no example for that.

### ISSUE THREAD

**Issue by shukla12manish** [tttstudios/react-native-otp-input#37]
**Describe the bug**
I added clearInputs as true but it is not working properly.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eramudeep** [comment]
I was also facing the same problem.
then i checked there is a prop called: **code**
so i used this in following way.
**Hope this Help**

`const [clearOtp, setClearOtp] = useState(false)
  const [otpToClear, setOtpToClear] = useState("")

<OTPInputView
          style={style.otpViewer}
          pinCount={6} 
          clearInputs={clearOtp} //tellng component to clear inputs 
          code={otpToClear} //setting otp from state to component
          
          onCodeChanged={code => {
            setOtpToClear(code) //setting otp to state on chnage
            if (MY_CONDITION_TO_PROCEED) { 
              signUp()
            }
          }}
          codeInputHighlightStyle={underlineStyleHighLighted}
          autoFocusOnLoad={false}
          onCodeFilled={code => {
            setOtp(code)
          }}
        />

 /*TO CLEAR OTP AND RESET TO EMPTY*/
onErrorFunction(){  
      setClearOtp(false) // lettting component know to clear otp now
      if (!clearOtp) {
        setOtpToClear("") // resetting the opt to blank or null
      }
}       `
