### ISSUE TITLE
Can't change the font Color. 

### ISSUE THREAD

**Issue by Gopisekaran** [tttstudios/react-native-otp-input#52]

**Comment by fpena** [comment]
@Gopisekaran can you please provide more information and a code example of what you're trying to achieve?

**Comment by BeckyWu220** [comment]
Hi @Gopisekaran you might want to try passing in `color` to `codeInputFieldStyle` props to the OTPInputView component. 
```
        <OTPInputView
          codeInputFieldStyle={{ color: 'red' }}
        />
```
<img width="432" alt="image" src="https://user-images.githubusercontent.com/16603120/76788499-4899d900-6778-11ea-8a6a-0411a4073158.png">

**Comment by BeckyWu220** [comment]
@Gopisekaran I hope the answer we posted earlier had helped you in resolving this issue. To keep the issues list clean. I will close this issue now. Thanks.
