### ISSUE TITLE
Syntax Error in styles.js -> 'styles' is not defined

### ISSUE THREAD

**Issue by joeyfigaro** [tttstudios/react-native-otp-input#53]
**Describe the bug**
styles.js is exporting something that hasn't been defined

**To Reproduce**
1. Import component from library
2. Start application/load component that's importing the OTPInput 

**Expected behavior**
N/A

**Screenshots**
![](https://p197.p4.n0.cdn.getcloudapp.com/items/6quBQX8z/Image+2020-03-05+at+1.46.31+PM.png?v=177e10f481d39356a44e39813747490b)

**Smartphone (please complete the following information):**
 - Device: Virtual/Simulated
 - OS: os x 10.15.1
 - Browser: Firefox
 - Version: 73.0.1 

**Additional context**
Using Expo 36.0.0 with some babel overrides:
```js
/* eslint-disable @typescript-eslint/no-var-requires */
module.exports = function(api) {
  api.cache(true)
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      ['babel-plugin-graphql-tag', { importName: 'graphql-tag-ts' }],
      '@babel/plugin-transform-modules-commonjs',
      [
        'babel-plugin-styled-components',
        {
          displayName: true
        }
      ]
    ],
    env: {
      production: {
        plugins: ['react-native-paper/babel']
      }
    }
  }
}

```

**Comment by Baron-ha** [comment]
I edit in node_modules @twotalltotems/react-native-otp-input/styles.js.
I relace 'export default StyleSheet.create' instead of export default styles = StyleSheet.create.
This is a basic error

**Comment by joeyfigaro** [comment]
[PR up](https://github.com/tttstudios/react-native-otp-input/pull/60)

**Comment by joeyfigaro** [comment]
It seemed like this project wasn't being maintained when I created it, so I added an `.editorconfig`—I can remove if you guys would prefer. :)

**Comment by BeckyWu220** [comment]
Hi @joeyfigaro  Thanks for contributing to the library. I would agree with removing the `.editorconfig` file. If you could make the change, we will merge it right away. Thanks!

**Comment by BeckyWu220** [comment]
Fixed in PR https://github.com/tttstudios/react-native-otp-input/pull/48
