### ISSUE TITLE
Is there any need of more setting for copy OTP from SMS on android physical devices?

### ISSUE THREAD

**Issue by MrQureshi** [tttstudios/react-native-otp-input#67]
**Describe the bug**
I got OTP for mobile verification but SMS notification does not show copy OTP. 
would you like to tell me that is there any need of extra setting or what I have to do for that?

**To Reproduce**
1. Go to mobile verification 
2. Click on verification
3. got OTP SMS with code
4. not show copy code on notification.

**Device**
android S7

**here is my code**
`<OTPInputView
                    style={{ width: '80%', height: 100 }}
                    pinCount={4}
                    autoFocusOnLoad
                    codeInputFieldStyle={styles.underlineStyleBase}
                    codeInputHighlightStyle={styles.underlineStyleHighLighted}
                    onCodeFilled={(code => mobileVerificationSendCode(code))}
                />`

![Screenshot_20200420-192720_GoSpark](https://user-images.githubusercontent.com/30835780/79764083-51b13380-833e-11ea-9ab7-dec589dd90bf.jpg)

**Comment by fareedagha** [comment]
facing same issue did you find solution to copy code from sms

**Comment by MrQureshi** [comment]
> facing same issue did you find solution to copy code from sms?

not now ... I'm trying react-native-sms-retriever . but failed to create hashes

**Comment by ericdao-ttt** [comment]
Hi @MrQureshi 

I think this problem is because the device. SamSung phones do not have the copy button when getting a message with code, however, no problem with Google Pixel etc.
