### ISSUE TITLE
Unable to set focus programmatically 

### ISSUE THREAD

**Issue by alex-mironov** [tttstudios/react-native-otp-input#68]
I use a controlled approach, so I store `code` in state and reset it in case of a verification error.

```
  const [code, setCode] = useState('') 
  const codeInputRef = useRef(null)

const onFulfill = (code) => {
  setCode('')
  codeInputRef.current.focusField(0)
}

render () {
  return (
      <OTPInputView
        ref={innerRef}
        autoFocusOnLoad
        onCodeFilled={onFulfill}
            onCodeChanged={setCode}
            code={code}
            innerRef={codeInputRef}
      />
  )
}
```

This seems to be working in the simulator, unfortunately it doesn't work on a real device.
Tested on iPhone 11 Pro

**Comment by alex-mironov** [comment]
@BeckyWu220 can you please support on this?

**Comment by BeckyWu220** [comment]
@alex-mironov  Could you please be more specific regarding what didn't work on your iPhone 11 Pro? For example, does it crash the app? or does it not receiving any validation code? or does it not filling the pin slots with the received validation code? This would help us understand your needs better. Thanks!

**Comment by alex-mironov** [comment]
sorry if it was unclear, but it looks like whenever I call this
```
  setCode('')
  codeInputRef.current.focusField(0)
```
the code is resetting fine, but unfortunately, the first input is not getting focused. and the last focused input also looses focus

**Comment by resting** [comment]
Need this feature too. When user resend otp, it should be able to focus on the first textinput.

**Comment by IPbianco** [comment]
The following seems to work:
```
resendCode() {
  this.setState({ code: '' });
  this._otpInput.focusField(0);
}

updateRef = (ref) => {
  this._otpInput = ref;
};

<OTPInputView
  ref={this.updateRef}
  ...
  ...
/>
```

**Comment by resting** [comment]
@IPbianco interesting, thanks! Didn't realise I can get the `ref` of the components just by passing `ref`.
My usage pattern with functional components:

```javascript
Screen = () => {
  const otpInputRef = createRef();

  const onResend = () => {
    setCode('')
    otpInputRef.current.focusField(0)
  }

  return (
    <OTPInputViewWrap ref={otpInputRef} ... />
    <Button title='Resend' onPress={onResend}} />
  )
}

OTPInputViewWrap = React.forwardref((props, ref) => {
  return (
    <OTPInputView ref={ref} ... />
  )
})
```

**Comment by Dartangel** [comment]
It's working for me. I used libraries @react-native-community/hooks for focus effect when we go to backgond and return to the app

const currentAppState = useAppState();

    useFocusEffect(useCallback(() => {
        setTimeout(() => {
            otpRef?.focusField(0);
        }, 500);
    }, [currentAppState]));
