### ISSUE TITLE
Clipboard has been extracted from react-native code module, use @react-native-community/clipboard for clipboard.

### ISSUE THREAD

**Issue by ShubhamsGeekyAnts** [tttstudios/react-native-otp-input#70]
**Describe the bug**
Clipboard has been extracted from react-native code module, use @react-native-community/clipboard for clipboard.

**To Reproduce**
1. Go to './dist/index.js'
2. Add module '@react-native-community/clipboard'
3. Change 'import { Clipboard } from "react-native"; to import Clipboard from "@react-native-community/clipboard";'

**Comment by Kailash23** [comment]
Same issue!
