### ISSUE TITLE
InputText Color not changing

### ISSUE THREAD

**Issue by vishnukanth** [tttstudios/react-native-otp-input#73]
When we set colour to input style, input text colour is not changing. Even selectionColor not working.

Checking in Android Emulator

Regards
vishnu

**Comment by sathwik77** [comment]
Yes, I have the same problem

**Comment by sathwik77** [comment]
its working when you add color property to `codeInputFieldStyle` .

**Comment by fpena** [comment]
@vishnukanth does it work when you set `codeInputFieldStyle`?

**Comment by sathwik77** [comment]
> @vishnukanth does it work when you set `codeInputFieldStyle`?

Yes, it works

**Comment by vinaynarayankutty** [comment]
How do I change the input container background color? At first it is white, then after filling the code it changes to gray
