### ISSUE TITLE
OTP code is being put into the first cell

### ISSUE THREAD

**Issue by alex-mironov** [tttstudios/react-native-otp-input#75]
Not really sure what am I doing wrong. When the user enters code manually it works properly. But if I press on code from SM it is being put into the first cell.

<img width="616" alt="Screen Shot 2020-05-18 at 23 34 36" src="https://user-images.githubusercontent.com/2544767/82257531-dfde0100-9960-11ea-9ffd-98ecc25ce71a.png">

 - OS: iOS

**Comment by ericdao-ttt** [comment]
Hi @alex-mironov,

We have tested the code from SMS, it still works properly.

**Comment by ericdao-ttt** [comment]
Duplicate https://github.com/tttstudios/react-native-otp-input/issues/34
