### ISSUE TITLE
Cursor is not moving back to previous box .

### ISSUE THREAD

**Issue by vgvishal538** [tttstudios/react-native-otp-input#8]
**Describe the bug**
I am using Kika keyboard for Xiaomi which is default keyboard for Redmi  6  Pro, and when I am pressing clear button on the keyboard the cursor is not moving back to the previous box.
I have tested a few other keyboards it seems fine but only for Kika keyboard your lib is not working.

**To Reproduce**
Use Kika keyboard for filling otp.

**Screenshots**
Check the video .
[issue video.zip](https://github.com/Twotalltotems/react-native-otp-input/files/3546082/issue.video.zip)

**Smartphone (please complete the following information):**
 - Device: [Redmi 6 pro]
 - OS: [Android 9 (pie)]
 

**Additional context**

**Comment by ansonyao** [comment]
Thanks for the video. Looks like the back button click is not picked up by the RN. Will look into this. But most likely, it is an issue in RN.

**Comment by Heru6664** [comment]
any update? i got same issue

**Comment by fpena** [comment]
@vgvishal538 what React Native version is this?

**Comment by tannguyen16** [comment]
I think the issue only happens to a newer version of Android. It works fine on Samsung Galaxy S3, but cannot move back on OnePlus 7 Pro. Works fine on iPhone also.

**Comment by vgvishal538** [comment]
> @vgvishal538 what React Native version is this?

 "react-native": "^0.60.4",

**Comment by AnchalMulchandani** [comment]
Is there any update for this issue? i got same issue

**Comment by ericdao37** [comment]
From [react-native document](https://reactnative.dev/docs/textinput.html#onkeypress)

There is a note: on Android only the inputs from soft keyboard are handled, not the hardware keyboard inputs.

That's why we have this issue. It just happens to the hardware keyboard inputs!

**Comment by AnchalMulchandani** [comment]
> From [react-native document](https://reactnative.dev/docs/textinput.html#onkeypress)
> 
> There is a note: on Android only the inputs from soft keyboard are handled, not the hardware keyboard inputs.
> 
> That's why we have this issue. It just happens to the hardware keyboard inputs!

Thanks! Its working :)

**Comment by ritu-tripathi-neo** [comment]
> From [react-native document](https://reactnative.dev/docs/textinput.html#onkeypress)
> 
> There is a note: on Android only the inputs from soft keyboard are handled, not the hardware keyboard inputs.
> 
> That's why we have this issue. It just happens to the hardware keyboard inputs!

this helped
