### ISSUE TITLE
Change Clipboard package from react-native to @react-native-community/clipboard.

### ISSUE THREAD

**Issue by pragyawebvillee** [tttstudios/react-native-otp-input#86]
@ericdao37 
Clipboard from react-native core is now deprecated.

Clipboard has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from \'@react-native-community/clipboard\' instead of \'react-native\'

Ref :  https://github.com/react-native-community/clipboard

**Comment by ericdao37** [comment]
Hi @pragyawebvillee 

We have changed to @react-native-community/clipboard.

Thank you
