### ISSUE TITLE
TypeError: null is not an object(evaluating 'NativeClipboard_1.default.getString')

### ISSUE THREAD

**Issue by sandeepg1220** [tttstudios/react-native-otp-input#88]
**Describe the bug**
Getting the error TypeError: null is not an object(evaluating 'NativeClipboard_1.default.getString')

**Smartphone (please complete the following information):**
 - Device: Android Honor 7X
 - OS: 9
 - Version: Checked in 1.3.11 or 
![1594734296316](https://user-images.githubusercontent.com/57384948/87433307-c8409300-c606-11ea-86e7-f6204a711479.JPEG)
1.3.7

**Comment by ajaymarathe9** [comment]
> **Describe the bug**
> Getting the error TypeError: null is not an object(evaluating 'NativeClipboard_1.default.getString')
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Android Honor 7X
> * OS: 9
> * Version: Checked in 1.3.11 or
>   ![1594734296316](https://user-images.githubusercontent.com/57384948/87433307-c8409300-c606-11ea-86e7-f6204a711479.JPEG)
>   1.3.7

Getting same issue any suggestion :(

**Comment by up-himanshu** [comment]
Getting the same error.

**Comment by avy-sha** [comment]
Same issue.

**Comment by ericdao-ttt** [comment]
Hi,

NOTES:
From version 1.3.10: We use @react-native-community/clipboard to handle the clipboard in this package, So you should install @react-native-community/clipboard
Please install @react-native-community/clipboard to fix this problem.

if you are using expo, we recommend changing to the older version 1.3.7 because expo does not support @react-native-community/clipboard.

Thank you!

**Comment by avy-sha** [comment]
Hey, 
I am already using "@react-native-community/clipboard": "^1.2.3". An also not using expo. Still getting the issue.

Os: Android 10
Device Oneplus 7

**Comment by Harikasai999** [comment]
hi,

i installed this "@react-native-community/clipboard": "^1.2.3" package still i am getting this error....

**Comment by up-himanshu** [comment]
Same here. Since my project is on RN 0.59, I just used version 1.3.7 and
removed ^.

*Himanshu*

**Comment by ajaymarathe9** [comment]
Hello guys, I was getting same issue, I debug for while, then used different library it's working fine.
use this -> `    "react-native-phone-input": "^0.2.4"`
Hope this helps you.

**Comment by avy-sha** [comment]
Hey, there was some error with the Gradle built itself. After I restarted Gradle daemon it resolved some dependencies of the clipboard and it started working.

**Comment by pravin-maan** [comment]
install this npm  @react-native-community/clipboard
working fine

**Comment by ZaidQ797** [comment]
Getting same issue but installing this lib @react-native-community/clipboard worked for me
