### ISSUE TITLE
autoFocusOnLoad not automatically bringing up keyboard on iOS

### ISSUE THREAD

**Issue by sonianigam** [tttstudios/react-native-otp-input#92]
**Describe the bug**
I am implementing a standard phone authentication flow. First I render a `TextInput` component to collect the phone number, and then I render an `OTPInputView` to collect the code. The standard `TextInput` autofocuses, but the `OTPInputView` does not. I have `autoFocusOnLoad` in my `OTPInputView`. I have also tried manually setting a ref and calling `focusField(0)`.

**Code**
```
<CodeInput
  ref={this.textInput}
  pinCount={6}
  autoFocusOnLoad
  keyboardType={"phone-pad"}
  codeInputFieldStyle={{
    width: 40,
    height: 40,
    borderWidth: 1,
    borderRadius: 20,
    padding: 0,
    margin: 0,
  }}
  codeInputHighlightStyle={{
    width: 40,
    height: 40,
    borderWidth: 4,
    borderRadius: 20,
    padding: 0,
    margin: 0,
  }}
  onCodeFilled={(code) => {
    this.confirmCode(code);
  }}
/>
```

**To Reproduce**
1. Enter phone number into `TextInput`
2. Click on next arrow
3. `OTPInputView` appears but does not autofocus

**Expected behavior**
I expected the OTPInputView to autofocus.

**Screenshots**

**Smartphone (please complete the following information):**
 - iPhone X
 - iOS 13.5.1

 - otp-input Version 1.3.11

![IMG_3527](https://user-images.githubusercontent.com/8127468/88835686-77927380-d18a-11ea-8efd-0647db04c945.PNG)
![IMG_3528](https://user-images.githubusercontent.com/8127468/88835923-cfc97580-d18a-11ea-9c2e-72932407b9a1.PNG)

**Comment by alex-mironov** [comment]
Can someone pls help with this? facing the same issue on iOS

**Comment by alex-mironov** [comment]
in my case I had to use `Keyboard.dismiss()`

**Comment by chengsam** [comment]
In my case I have to dismiss the keyboard on phone number input page then wait for 1 second before going to top page

`Keyboard.dismiss();
setTimeout(() => {
  navigation.navigate('nextPage');
}, 1000);`
